### ISSUE TITLE
[question] Disable onepage on mobile?

### ISSUE THREAD

**Issue by zoran119** [peachananr/onepage-scroll#129]
When viewing your demo page on a mobile device, it seems that `onepage-scroll` is disabled (no little indicators on the right and there is no auto-scrolling). How to get this behaviour?

Great plugin by the way :)

**Comment by akalightowl** [comment]
I think this issue can be closed. responsiveFallback work awesome, like all this plugin! Thank you for this option. 

> responsiveFallback: 1024

 solve all my mobile problem
