### ISSUE TITLE
IE8/IE9 Not working

### ISSUE THREAD

**Issue by domialex** [peachananr/onepage-scroll#193]
I can't get this plugin to work on IE8/IE9 even with modernizr. (Even the demo doesn't work)
Weirdly enough, the version v1 works...

EDIT: The code is looking for the class "ie8" in the html. Even if modernizr adds this class, it still won't work in IE9.

My fix: Look for the "no-csstransforms3d" class instead.

**Comment by AnastasiaLozhachevskaya** [comment]
I've just added a string in line 100
if($('html').hasClass('ie8') || navigator.userAgent.indexOf('MSIE 9.') > 0){
and it worked
