### ISSUE TITLE
Bootstrap Modal does not work

### ISSUE THREAD

**Issue by anteloff** [peachananr/onepage-scroll#235]
Hi,
is there any way to make Bootstrap modal work with onepage-scroll plugin?

Thanks

**Comment by sutharphp** [comment]
Yes ,
Skype:- sumit.suthar2

-----Original Message-----

**Comment by anteloff** [comment]
Can you please write your solution here?

**Comment by anteloff** [comment]
I've managed to solve this issue using this css:

	.modal{
		position: absolute;
	}
	.modal-backdrop{
		position: relative;
	}
