### ISSUE TITLE
scroll to section 2 when click button

### ISSUE THREAD

**Issue by helga-hai** [peachananr/onepage-scroll#323]
How I make scroll to section 2 when click button (Section 1)?

    $('.reload.btn').bind('click', function(){
         $(".main").moveTo(2);
    });

This not work.

**Comment by Veeraiyan-Tanke** [comment]
$(".anim-mouse").on("click", function() {

        var section_index = $('.main section.active').index();
        var section_length = $('.main section').length - 1;

        console.log(section_length);
        console.log(section_index);

        if (section_index == section_length) {
            $(".main").moveTo(0);
        }
        $('.main').moveDown();
    });

**Comment by helga-hai** [comment]
Thank you very much for the answer.
The scroll is happening.
But when I press the button - the page reloads.
Why is this happening?

**Comment by Veeraiyan-Tanke** [comment]
try this code

$('.reload.btn').bind('click', function(e){
     $(".main").moveTo(2);
e.preventdefault();
});

and if you using a tag then you need to provide the value like <a href="#!"></a>

**Comment by helga-hai** [comment]
Thanks.
It worked.
